$:
  vscode:
    - imports:
        - https://cnb.cool/arsrna/env/-/blob/main/git.yaml
      runner:
        cpus: 16
      docker:
        image: docker.cnb.cool/arsrna/dev-env/node22
      services:
        - vscode
        - docker
      stages:
        - name: install
          script: pnpm i
  push:
    pipeline-1:
      runner:
        cpus: 16
      docker:
        image: docker.cnb.cool/arsrna/dev-env/node22
      services:
        - docker
      imports:
        - https://cnb.cool/arsrna/env/-/blob/main/git.yaml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/ArSrNa/react-genshin-website.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_email: "root@arsrna.cn"
            # force: true
    tag_deploy.production:
      runner:
        cpus: 32
      imports: https://cnb.cool/arsrna/env/-/blob/main/tencent.yml
      stages:
        - name: build
          image: node:20-alpine
          script:
            - npm i -g pnpm
            - pnpm i
            - npm run build
        - name: 部署我的 eo pages 正式环境
          image: docker.cnb.cool/looc/deploy-eopages:latest
          script: edgeone pages deploy ./out -t $EO_SECRET
